name: setup-gflows
description: Install GitHub Workflow Templates (GFlows)
author: John Brunton
branding:
  color: green
  icon: play
inputs:
  token:
    description: "Github token to use to avoid rate limits"
    required: false
    default: ""
  version:
    description: "The version of GFlows to install (default: latest)"
    required: false
    default: latest
  github-api-url:
    description: 'configure github API URL. Default `https://api.github.com`'
    required: false
    default: 'https://api.github.com'
runs:
  using: 'node12'
  main: 'dist/index.js'
