# Config file for GFlows.
# See https://github.com/jbrunton/gflows/wiki/Configuration for options.
githubDir: .github
templates:
  engine: ytt
  defaults:
    dependencies:
      - git@github.com:jbrunton/gflows-libs.git/tag-release
